language: node_js
node_js:
  - "v10.11.0"
branches:
  only:
  - gitbook_blog
notifications:
  email:
    recipients:
      - 1058862172@qq.com
      - zhishengqianjun@163.com
    on_success: always # default: change
    on_failure: always # default: alway
cache:
  directories:
  - node_modules
  yarn: true
before_install:
- export TZ='Asia/Shanghai'  # 设置时区
install:
 - npm install -g gitbook-cli
script:
- gitbook install
- gitbook build
  #deploy:
  #  provider: pages
  #  skip-cleanup: true
  #  github-token: $GH_TOKEN
  #  local-dir: ./_book/ ## 根据情况自定义到静态文件输出目录
  #  target-branch: gitbook_blog
  #  verbose: true
  #  on:
  #    branch: master

after_script:
   - cd ./_book
   - git init
   - git config user.name "zhishengqianjun"
   - git config user.email "zhishengqianjun@163.com"
   - git add .
   - git commit -m "Update Gitbook By TravisCI With Build $TRAVIS_BUILD_NUMBER"
   - git push --force --quiet "https://zhishengqianjun:${CO_TOKEN}@${CO_REF}" master:master
   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

env:
 global:
   # Coding Pages
   - CO_REF: git.dev.tencent.com/zhishengqianjun/blog.git
   - GH_REF: github.com/gaviners/gaviners.github.io.git

